export const PLAYERS = [
  'ElderPlinius', 'Brec', 'IronDethaele', 'Gooner1212',
  'IronPlinius', 'Plinybis', 'Dr Moon Law', 'TealBingo',
  'DrPlingo0', 'state 0',
]

export const SKILLS = [
  { key: 'Overall', label: 'Overall' },
  { key: 'Attack', label: 'Attack' },
  { key: 'Defence', label: 'Defence' },
  { key: 'Strength', label: 'Strength' },
  { key: 'Hitpoints', label: 'Hitpoints' },
  { key: 'Ranged', label: 'Ranged' },
  { key: 'Prayer', label: 'Prayer' },
  { key: 'Magic', label: 'Magic' },
  { key: 'Cooking', label: 'Cooking' },
  { key: 'Woodcutting', label: 'Woodcutting' },
  { key: 'Fletching', label: 'Fletching' },
  { key: 'Fishing', label: 'Fishing' },
  { key: 'Firemaking', label: 'Firemaking' },
  { key: 'Crafting', label: 'Crafting' },
  { key: 'Smithing', label: 'Smithing' },
  { key: 'Mining', label: 'Mining' },
  { key: 'Herblore', label: 'Herblore' },
  { key: 'Agility', label: 'Agility' },
  { key: 'Thieving', label: 'Thieving' },
  { key: 'Slayer', label: 'Slayer' },
  { key: 'Farming', label: 'Farming' },
  { key: 'Runecrafting', label: 'Runecrafting' },
  { key: 'Hunter', label: 'Hunter' },
  { key: 'Construction', label: 'Construction' },
]

export const ACTIVITIES = [
  { key: 'AbyssalSire', label: 'Abyssal Sire' },
  { key: 'AlchemicalHydra', label: 'Alchemical Hydra' },
  { key: 'BarrowsChests', label: 'Barrows Chests' },
  { key: 'BountyHunter_Hunter_Legacy', label: 'Bounty Hunter (Legacy) - Hunter' },
  { key: 'BountyHunter_Rogue_Legacy', label: 'Bounty Hunter (Legacy) - Rogue' },
  { key: 'BountyHunter_Hunter', label: 'Bounty Hunter - Hunter' },
  { key: 'BountyHunter_Rogue', label: 'Bounty Hunter - Rogue' },
  { key: 'Calvarion', label: "Calvar'ion" },
  { key: 'ChambersofXeric', label: 'Chambers of Xeric' },
  { key: 'ChambersofXeric_ChallengeMode', label: 'Chambers of Xeric: Challenge Mode' },
  { key: 'ChaosElemental', label: 'Chaos Elemental' },
  { key: 'ChaosFanatic', label: 'Chaos Fanatic' },
  { key: 'ClueScrolls_all', label: 'Clue Scrolls (all)' },
  { key: 'ClueScrolls_beginner', label: 'Clue Scrolls (beginner)' },
  { key: 'ClueScrolls_easy', label: 'Clue Scrolls (easy)' },
  { key: 'ClueScrolls_medium', label: 'Clue Scrolls (medium)' },
  { key: 'ClueScrolls_hard', label: 'Clue Scrolls (hard)' },
  { key: 'ClueScrolls_elite', label: 'Clue Scrolls (elite)' },
  { key: 'ClueScrolls_master', label: 'Clue Scrolls (master)' },
  { key: 'CollectionsLogged', label: 'Collections Logged' },
  { key: 'ColosseumGlory', label: 'Colosseum Glory' },
  { key: 'CommanderZilyana', label: 'Commander Zilyana' },
  { key: 'CorporealBeast', label: 'Corporeal Beast' },
  { key: 'CrazyArchaeologist', label: 'Crazy Archaeologist' },
  { key: 'DagannothPrime', label: 'Dagannoth Prime' },
  { key: 'DagannothRex', label: 'Dagannoth Rex' },
  { key: 'DagannothSupreme', label: 'Dagannoth Supreme' },
  { key: 'DeadmanPoints', label: 'Deadman Points' },
  { key: 'DerangedArchaeologist', label: 'Deranged Archaeologist' },
  { key: 'DoomOfMokhaiotl', label: 'Doom of Mokhaiotl' },
  { key: 'DukeSucellus', label: 'Duke Sucellus' },
  { key: 'GeneralGraardor', label: 'General Graardor' },
  { key: 'GiantMole', label: 'Giant Mole' },
  { key: 'GridPoints', label: 'Grid Points' },
  { key: 'GrotesqueGuardians', label: 'Grotesque Guardians' },
  { key: 'GuardiansOfTheRift', label: 'Guardians of the Rift' },
  { key: 'KalphiteQueen', label: 'Kalphite Queen' },
  { key: 'KingBlackDragon', label: 'King Black Dragon' },
  { key: 'KreeArra', label: "Kree'Arra" },
  { key: 'KrilTsutsaroth', label: "K'ril Tsutsaroth" },
  { key: 'LMS_Rank', label: 'LMS - Rank' },
  { key: 'LeaguePoints', label: 'League Points' },
  { key: 'LunarChests', label: 'Lunar Chests' },
  { key: 'PhantomMuspah', label: 'Phantom Muspah' },
  { key: 'PhosanisNightmare', label: "Phosani's Nightmare" },
  { key: 'PvPArena', label: 'PvP Arena - Rank' },
  { key: 'ShellbaneGryphon', label: 'Shellbane Gryphon' },
  { key: 'SolHeredit', label: 'Sol Heredit' },
  { key: 'SoulWars_Zeal', label: 'Soul Wars Zeal' },
  { key: 'TheCorruptedGauntlet', label: 'The Corrupted Gauntlet' },
  { key: 'TheGauntlet', label: 'The Gauntlet' },
  { key: 'TheHueycoatl', label: 'The Hueycoatl' },
  { key: 'TheLeviathan', label: 'The Leviathan' },
  { key: 'TheRoyalTitans', label: 'The Royal Titans' },
  { key: 'TheWhisperer', label: 'The Whisperer' },
  { key: 'TheatreofBlood', label: 'Theatre of Blood' },
  { key: 'TheatreofBlood_HardMode', label: 'Theatre of Blood: Hard Mode' },
  { key: 'ThermonuclearSmokeDevil', label: 'Thermonuclear Smoke Devil' },
  { key: 'TombsOfAmascut', label: 'Tombs of Amascut' },
  { key: 'TombsOfAmascutExpert', label: 'Tombs of Amascut: Expert Mode' },
  { key: 'TzKalZuk', label: 'TzKal-Zuk' },
  { key: 'TzTokJad', label: 'TzTok-Jad' },
  { key: 'Vettion', label: "Vet'ion" },
]
