"""Useful OSRS Metrics Constants."""
# Map JSON API skill names to legacy DB format
LEGACY_SKILL_MAP = {
    "Runecraft": "Runecrafting",
}

# Map JSON API activity names to legacy DB format
LEGACY_ACTIVITY_MAP = {
    "Abyssal Sire": "AbyssalSire",
    "Alchemical Hydra": "AlchemicalHydra",
    "Barrows Chests": "BarrowsChests",
    "Bounty Hunter (Legacy) - Hunter": "BountyHunter_Hunter_Legacy",
    "Bounty Hunter (Legacy) - Rogue": "BountyHunter_Rogue_Legacy",
    "Bounty Hunter - Hunter": "BountyHunter_Hunter",
    "Bounty Hunter - Rogue": "BountyHunter_Rogue",
    "Calvar'ion": "Calvarion",
    "Chambers of Xeric": "ChambersofXeric",
    "Chambers of Xeric: Challenge Mode": "ChambersofXeric_ChallengeMode",
    "Chaos Elemental": "ChaosElemental",
    "Chaos Fanatic": "ChaosFanatic",
    "Clue Scrolls (all)": "ClueScrolls_all",
    "Clue Scrolls (beginner)": "ClueScrolls_beginner",
    "Clue Scrolls (easy)": "ClueScrolls_easy",
    "Clue Scrolls (medium)": "ClueScrolls_medium",
    "Clue Scrolls (hard)": "ClueScrolls_hard",
    "Clue Scrolls (elite)": "ClueScrolls_elite",
    "Clue Scrolls (master)": "ClueScrolls_master",
    "Collections Logged": "CollectionsLogged",
    "Colosseum Glory": "ColosseumGlory",
    "Commander Zilyana": "CommanderZilyana",
    "Corporeal Beast": "CorporealBeast",
    "Crazy Archaeologist": "CrazyArchaeologist",
    "Dagannoth Prime": "DagannothPrime",
    "Dagannoth Rex": "DagannothRex",
    "Dagannoth Supreme": "DagannothSupreme",
    "Deadman Points": "DeadmanPoints",
    "Deranged Archaeologist": "DerangedArchaeologist",
    "Doom of Mokhaiotl": "DoomOfMokhaiotl",
    "Duke Sucellus": "DukeSucellus",
    "General Graardor": "GeneralGraardor",
    "Giant Mole": "GiantMole",
    "Grid Points": "GridPoints",
    "Grotesque Guardians": "GrotesqueGuardians",
    "K'ril Tsutsaroth": "KrilTsutsaroth",
    "Kalphite Queen": "KalphiteQueen",
    "King Black Dragon": "KingBlackDragon",
    "Kree'Arra": "KreeArra",
    "LMS - Rank": "LMS_Rank",
    "League Points": "LeaguePoints",
    "Lunar Chests": "LunarChests",
    "Phantom Muspah": "PhantomMuspah",
    "Phosani's Nightmare": "PhosanisNightmare",
    "PvP Arena - Rank": "PvPArena",
    "Rifts closed": "GuardiansOfTheRift",
    "Shellbane Gryphon": "ShellbaneGryphon",
    "Sol Heredit": "SolHeredit",
    "Soul Wars Zeal": "SoulWars_Zeal",
    "The Corrupted Gauntlet": "TheCorruptedGauntlet",
    "The Gauntlet": "TheGauntlet",
    "The Hueycoatl": "TheHueycoatl",
    "The Leviathan": "TheLeviathan",
    "The Royal Titans": "TheRoyalTitans",
    "The Whisperer": "TheWhisperer",
    "Theatre of Blood": "TheatreofBlood",
    "Theatre of Blood: Hard Mode": "TheatreofBlood_HardMode",
    "Thermonuclear Smoke Devil": "ThermonuclearSmokeDevil",
    "Tombs of Amascut": "TombsOfAmascut",
    "Tombs of Amascut: Expert Mode": "TombsOfAmascutExpert",
    "TzKal-Zuk": "TzKalZuk",
    "TzTok-Jad": "TzTokJad",
    "Vet'ion": "Vettion",
}
